### ISSUE TITLE
Change the order of the inventory items in the inventory table

### ISSUE THREAD

**Issue by Norbbs** [fjborquez/azula#42]
**As a** User
**I want to** see the inventory items sorted in a better priotiizing the products approaching expired
**So that** I can take quick actions and not generate waste and loss my food.

### Scope
> 1. The order of the items should be as follows:

    1.     Sort by purchase date from the oldest to the most recent (ASC)
    2.     Sort by status: 
            i. Approaching to expire
            ii. Fresh 
            iii. Undefined 
            iv. Expired
    3.     Sort by expiration date from the oldest to the most recent (ASC)
    4.     Sort by catalog description (ASC)

> 2. Items with status consumed and discarded (with a status where (is_final_phase = 1) should not appear in the listing.
> 3. Look at the SQL script:
```
SELECT CONCAT(i.quantity, ' ', i.uom_abbreviation) AS qty,
       i.brand_name AS brand,
       i.catalog_description,
       i.purchase_date,
       i.expiration_date,
       ps.id,
       ps.description
FROM inventories i
INNER JOIN product_status_transitions pst ON pst.inventory_id = i.id
INNER JOIN product_status ps ON pst.product_status_id = ps.id
WHERE i.house_id = ? AND pst.is_active = 1 AND ps.is_final_phase IS FALSE
ORDER BY i.purchase_date,
         CASE ps.id
              WHEN 2 /* Approaching Expiry */ THEN 1
              WHEN 1 /* Fresh */ THEN 2
              WHEN 6 /* Undefined */ THEN 3
              WHEN 3 /* Expired */ THEN 4
         END,
         i.expiration_date,
         i.catalog_description;
```

### Out of scope
> 1. Any others order factors not mentioned in the scope section

### Result (example)
![Image](https://github.com/user-attachments/assets/6a78d518-8a0d-4bfd-91e7-5e8343428a34)

**Comment by Norbbs** [comment]
The "expiration date" column is not being sorted as it should be.
The products purchased on "09/09/2024" should be ordered from 10/18/2024 to 10/12/2024 and not the other way around.
As in the following example:
[![Image](https://github.com/user-attachments/assets/981239cb-15c8-4630-82e0-9ad78b46fce3)
](url)

@fjborquez

**Comment by Norbbs** [comment]
Please add an addional order by criteria _"i.catalog_description"_ ... the query was modified. @fjborquez

**Comment by fjborquez** [comment]
Fixed according specifications. Please, check it.

**Comment by Norbbs** [comment]
The inventory order is still not working

at this time (17-11-2024), the oaks' house should be like this:

![Image](https://github.com/user-attachments/assets/be501867-bcfd-46f5-b816-750a8e162fe5)

but it looks like this:

![Image](https://github.com/user-attachments/assets/b3c8e800-fb98-4053-a3d4-f48b5867fdeb)

@fjborquez
